### ISSUE TITLE
Error when requesting unpkg.com/isomorphic.js@0.1.4?module

### ISSUE THREAD

**Issue by blixt** [dmonad/isomorphic.js#3]
Requesting https://unpkg.com/isomorphic.js@0.1.4?module results in the error:
> Package isomorphic.js@0.1.4 does not contain an ES module

This appears to be the main blocker from being able to use Yjs fully as an ES module.

**Comment by dmonad** [comment]
Hi @blixt 

I added an esm package for this package in 0.1.5. Hope this works now for you.

> The Yjs project is non-profit and needs your support. If you like the software, please consider sponsoring me on https://github.com/sponsors/dmonad
